### ISSUE TITLE
Livechan broken, halp pls!

### ISSUE THREAD

**Issue by live4livechan** [emgram769/livechan-js#143]
We can't attach any file to post, it only return

> could not process file at this time (probably server stress)

fix please, be kind to us ;-;
And Anna wikibot ded too, would be nice if we meet her again. Thx.

**Comment by live4livechan** [comment]
Now i can't open site at all
>Error: EMFILE, open 'pages/index.html'

**Comment by Dagrotwiffdabigchoppa** [comment]
Yeah some issues posting images, sometimes I can't even post at all without refreshing. Also RIP anna ;-;7
