### ISSUE TITLE
build fails on ubuntu 18.04, tested with multiple node versions

### ISSUE THREAD

**Issue by piguet** [emgram769/livechan-js#161]
I am trying to give this a spin but I am unable to get it to work.
Environment: ubuntu 18.04, tested with node 12, 4.x, 6.x, 0.x.
Errors: Failed at the canvas@1.1.6 install script, Failed at the geoapi install script.

What's the environment used for livebunker an kotchan?

**Comment by slavking** [comment]
```
kotchan:~$ node -v
v0.10.25
kotchan:~$ npm -v
1.3.10

```
Operating system is Ubuntu 14.04.05 LTS

It also uses some outdated library, not sure which one. I can post the `npm list` if you require it.

**Comment by pawnhearts** [comment]
Yes it only works on ubuntu 14.04 or equally ancient debian. Since it's end of line support idk maybe it's safer to make dockerfile so it would run on 14.04 inside container.
If there are some node developers willing to port it to mode recent node I would gladly accept such patches.
@slavking I believe library versions are locked in package.json stuff. It's anna which doesn't work on recent versions of python-socketio.

**Comment by pawnhearts** [comment]
idk maybe I should provide a Dockerfile which can run it. If I have some time I would do it.

**Comment by piguet** [comment]
> idk maybe I should provide a Dockerfile which can run it. If I have some time I would do it.
Unfortunately I am a noob but I will try to see if I am able to make the dockerfile, otherwise I should find a vps with ubuntu 14.04, thanks! It's a beautiful script and I think it could work well as a mobile-centric irc-imageboard hybrid

**Comment by pawnhearts** [comment]
irc gate works like shit tbh. There is a working telegram gate but it never were published. It needs some reworking first.

**Comment by piguet** [comment]
>There is a working telegram gate 

That's awesome

**Comment by piguet** [comment]
> ```
> kotchan:~$ node -v
> v0.10.25
> kotchan:~$ npm -v
> 1.3.10
> ```
> Operating system is Ubuntu 14.04.05 LTS
> 
> It also uses some outdated library, not sure which one. I can post the `npm list` if you require it.

Tested with ubuntu 14.04, with the above configuration... **npm start** fails because in some socket.io-stream module there are arrow functions and they are not interpreted by older versions of node.. but if I update node other modules won't install. Very weird

**Comment by piguet** [comment]
ok fixed converting arrow functions to regular functions in socket.io-stream. 
works on 14.04 with the node version specified by slavking
